services:
  - type: web
    name: chat-app-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://rishabhmavi:rishabhmavi123@cluster0.hnjphl3.mongodb.net
      - key: JWT_SECRET
        value: gs#secret
      - key: CLOUDINARY_CLOUD_NAME
        value: dtufb2qe4
      - key: CLOUDINARY_API_KEY
        value: "372745721515616"
      - key: CLOUDINARY_API_SECRET
        value: wwOzIXeIm-HICoxMVvCOBFnDpdk

  - type: static
    name: chat-app-frontend
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://chat-app-backend.onrender.com
