@echo off
echo Starting Chat App Development Servers...
echo.
echo Starting Server on port 5000...
start "Server" cmd /k "cd server && npm run server"
echo.
echo Starting Client on port 3000...
start "Client" cmd /k "cd client && npm run dev"
echo.
echo Both servers are starting...
echo Server: http://localhost:5000
echo Client: http://localhost:3000
echo.
echo Press any key to close this window...
pause >nul
